name: SuperDragonEgg
version: '1.0.0'
main: com.NguyenDevs.superDragonEgg.SuperDragonEgg
api-version: '1.20'
description: Grants buffs to players holding dragon egg, debuffs to nearby entities, and radar wave particle effects
commands:
  sde:
    description: SuperDragonEgg plugin commands
    usage: /<command> reload
permissions:
  superdragonegg.reload:
    description: Allows reloading the SuperDragonEgg config
    default: op