name: SuperDragonEgg
version: '1.0.2'
main: com.NguyenDevs.superDragonEgg.SuperDragonEgg
api-version: '1.20'
description: Grants buffs to players holding dragon egg, debuffs to nearby entities
commands:
  sde:
    description: SuperDragonEgg plugin commands
    usage: /<command> reload
permissions:
  sde.reload:
    description: Allows reloading the SuperDragonEgg config
    default: op
  sde.bypass:
    description: Allows to bypass debuff, knockback and ability effect
    default: op
  sde.use:
    description: Allows using the SuperDragonEgg features
    default: true